### ISSUE TITLE
Issue #4 peer reviewed papers: wrong URL

### ISSUE THREAD

**Issue by trox** [trox/JoPP#1]
the link appears to be absolute to peerproduction.net, not relative to site on http://peerproduction-net.preview1.cp247.net/editsuite/issues/issue-4-value-and-currency/

**Comment by maxigas** [comment]
I guess the same is happening whereever content comes from a textarea -- such as the "submission" link on the About page: http://peerproduction-net.preview1.cp247.net/editsuite/about/

**Comment by maxigas** [comment]
the single link in the content area of this page is absolute too:

http://peerproduction-net.preview1.cp247.net/editsuite/projects/books/

as well as the ones here:

http://peerproduction-net.preview1.cp247.net/editsuite/projects/

**Comment by maxigas** [comment]
the download link here is absolute too:

http://peerproduction-net.preview1.cp247.net/editsuite/projects/books/book-of-peer-production/

**Comment by maxigas** [comment]
Translation page has links to the original articles on the jopp website, also absolute:

http://peerproduction-net.preview1.cp247.net/editsuite/projects/translations/

**Comment by maxigas** [comment]
I guess many others (so maybe do global replace) are absolute too, such as pages with the original download link:

http://peerproduction-net.preview1.cp247.net/editsuite/issues/issue-0/peer-reviewed-papers/the-origins-and-impacts-of-swedish-filesharing/original/

**Comment by trox** [comment]
This looks like a somewhat bigger issue, I just found about 1300 http://peerproduction.net URLs in all pages (includes links to images etc.); so global replace needs some careful planning, execution and testing.

**Comment by trox** [comment]
I have now changed all URLs in the editsuite to match the editsuite URL; from a first test this appears to be working.
