### ISSUE TITLE
Reviews page theming broken

### ISSUE THREAD

**Issue by maxigas** [trox/JoPP#3]
Reviews should be rendered by the theme based on the reviews in the database.

Sample URL:

http://peerproduction-net.preview1.cp247.net/editsuite/issues/issue-0/peer-reviewed-papers/the-origins-and-impacts-of-swedish-filesharing/reviews/

**Comment by trox** [comment]
again I guess this used to be a tabbed page (could you confirm, please)

**Comment by maxigas** [comment]
Confirmed. You can see how it was in the archive:

http://web.archive.org/web/20140724094610/http://peerproduction.net/issues/issue-0/peer-reviewed-papers/the-origins-and-impacts-of-swedish-filesharing/reviews/

**Comment by trox** [comment]
same issue as #5; closing #5

**Comment by ptroxler** [comment]
It appears that the theme which we’ve got installed is not the same theme that is presented on the archive.org mirror.
Evidence: abs on archive.org are styled with <span> tags, tabs on site are styled with <li> tags
Fact: the theme we’ve received from Javier is not the theme that generated the archive.org pages (Aug 1, 2014)

**Comment by trox** [comment]
It appears that the theme which we’ve got installed is not the same theme that is presented on the archive.org mirror.
Evidence: tabs on archive.org are styled with span-tags, tabs on site are styled with li-tags
Fact: the theme we’ve received from Javier is not the theme that generated the archive.org pages (Aug 1, 2014)

**Comment by trox** [comment]
Appearance can be easily achieved with a plugin called "Tabby Responsive Tabs” from https://wordpress.org/plugins/tabby-responsive-tabs/
search & replace:
[tabs style=“1”] => ‘’
[tab => [tabby
[/tab] => ‘’
[/tabs] => [tabbyending]

**Comment by trox** [comment]
executing:
backup database .... done
[tabs style=“1”] => ‘’ .... done
[tab => [tabby .... done
[/tab] => ‘’ .... done
[/tabs] => [tabbyending] .... done

**Comment by trox** [comment]
all search & replace done, that means that review and signals pages should be back to tabbed.
not “fixed” is the styling issue, wontfix

**Comment by trox** [comment]
By the way ... apparently the implementation of the [tabs] tags was inconsistent across issues for the signal pages (mostly commendations were not presented as individual tabs), so I added the “Commendations” tab manually (and amended it from “Commendation” to “Commendations” where appropriate). As a result, there are papers with an empty “Commendations” section. Take that as a warning :p
