### ISSUE TITLE
PDF link should render paper not just title and abstract

### ISSUE THREAD

**Issue by maxigas** [trox/JoPP#4]
PDF rendering is known to be flaky. The body of the paper dissappears for instance clicking the links on the following page:

http://peerproduction-net.preview1.cp247.net/editsuite/issues/issue-0/peer-reviewed-papers/

**Comment by trox** [comment]
As we plan to replace the PDF plugin anyway I’ll close this ticket as wontfix

**Comment by maxigas** [comment]
Right, makes sense!
