### ISSUE TITLE
Signals page theming broken

### ISSUE THREAD

**Issue by maxigas** [trox/JoPP#5]
The issue here is the lack of theming for the "earmarks". Sample:

http://peerproduction-net.preview1.cp247.net/editsuite/issues/issue-0/peer-reviewed-papers/the-origins-and-impacts-of-swedish-filesharing/signals/

**Comment by trox** [comment]
I don’t get what you mean by “earmarks” -- it could be that this used to be a tabbed page, could you elaborate?

**Comment by maxigas** [comment]
Indeed, it was a tabbed page! Sorry I didn't remember the word "tab". Again, look here:

http://web.archive.org/web/20140306215816/http://peerproduction.net/issues/issue-0/peer-reviewed-papers/the-origins-and-impacts-of-swedish-filesharing/signals/

**Comment by trox** [comment]
same issue as #3; closing #5
