### ISSUE TITLE
Outdated PDF plugin

### ISSUE THREAD

**Issue by maxigas** [trox/JoPP#7]
I see that the PDF plugin is outdated and we had a lot of trouble with it. There seems to be many alternatives, although I have not tested them.  I don't know if you have experience with any, but I can do a shortlist and see which one to recommend for trying to replace the current one.

I understand that the features we are looking for are the following:

"PDF button" on pages.

"Templating" to add the JoPP header and footer, page numbers, etc. to the PDF output.

"Unicode / UTF-8 compatibility" because that is what breaks the current plugin, as far as I remember.

Anything else?

**Comment by trox** [comment]
I think these are the requirements ... rest is down to testing (rendering of tables, images used to be somewhat shaky)
Looking forward to the shortlist :)

**Comment by maxigas** [comment]
OK, I do some testing and deliver a few alternatives and one favourite until the end of February at the worst. I try to do it asap though.

**Comment by trox** [comment]
won’t fix as it appears to work as per communication of JoPP #8 / feminism issue editors.
